### ISSUE TITLE
Improve description of ab-connection-003

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#64]
Hi Achim,

I'm confused by `ab-connection-003.xml`. It claims to fail with `err:XD0007` but...

1. If it fails at all, surely it must fail statically
2. err:XD0007 doesn't exist
3. Didn't we recently decide that unconnected outputs were ok?

**Comment by xml-project** [comment]
Just to be sure: It is this test?
````
<p:declare-step version="3.0" xmlns:p="http://www.w3.org/ns/xproc">
      <p:output port="result" primary="false"/>
      
      <p:identity>
        <p:with-input port="source">
          <doc />
        </p:with-input>
      </p:identity>
    </p:declare-step>
````
Sorry, the description might be misleading, but I think the test is right.

ad 1. I think it should fail dynamically, because the pipelines output port "result" has sequence="false" and you can not know (in general) from a static analysis, if exactly one document arrives on "result".

ad 2. In the the specs and the error wiki there is an error XD0007, saying:

> If sequence is not specified on p:output, or has the value false, then it is a dynamic error if the step does not produce exactly one document on the declared port.

ad 3. I am not sure how this is relevant. Since `result/@primary` is false, there never was an implicitly factored connection between the last step of the subpipeline and the output port. This is what the test is supposed to test.

What did I miss?

**Comment by ndw** [comment]
I did get mislead by the description. (I'll make a PR to improve it.)
I have no idea why I didn't find XD0007. Maybe I was browsing the steps spec and didn't notice.
You didn't miss anything. Thank you.
